language: node_js
sudo: false
dist: trusty
cache: yarn

script:
  - yarn danger
  - yarn test

notifications:
  slack: wizeline:NqBcWNFLBaluqsCWyjVNcwyh
  webhooks:
    urls:
      - https://wizeline-webhooks.appspot.com/travis/notifications
