language: node_js
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules

script:
  - node --version
  - yarn --version
  # Tests have to run before Danger runs because
  # danger-plugin-jest references the test output
  - yarn run test
  - yarn run danger run -- --verbose

notifications:
  slack: wizeline:NqBcWNFLBaluqsCWyjVNcwyh
  webhooks:
    urls:
      - https://wizeline-webhooks.appspot.com/travis/notifications
