language: node_js
sudo: false
dist: trusty
cache: yarn

before_install:
  - npm install npm@latest -g

before_script:
  - sh -e /etc/init.d/xvfb start
  - yarn danger

script:
  - npm test

notifications:
  slack: wizeline:NqBcWNFLBaluqsCWyjVNcwyh
  webhooks:
    urls:
      - https://wizeline-webhooks.appspot.com/travis/notifications
