language: node_js
sudo: false
dist: trusty
cache: yarn

before_install:
  - npm install npm@latest -g

script:
  - yarn danger
  - npm test

notifications:
  slack: wizeline:NqBcWNFLBaluqsCWyjVNcwyh
  webhooks:
    urls:
      - https://wizeline-webhooks.appspot.com/travis/notifications
