// @flow

const BACKGROUND_PRIMARY = 'backgroundPrimary';
const BACKGROUND_PRIMARY_HOVER = 'backgroundPrimaryHover';
const BACKGROUND_PRIMARY_DISABLED = 'backgroundPrimaryDisabled';
const BACKGROUND_SECONDARY = 'backgroundSecondary';
const BACKGROUND_SECONDARY_HOVER = 'backgroundSecondaryHover';
const BACKGROUND_SECONDARY_DISABLED = 'backgroundSecondaryDisabled';
const BACKGROUND_DANGER = 'backgroundDanger';
const BACKGROUND_DANGER_HOVER = 'backgroundDangerHover';
const BACKGROUND_DANGER_DISABLED = 'backgroundDangerDisabled';
const BACKGROUND_INPUT = 'backgroundInput';

export default {
  BACKGROUND_PRIMARY,
  BACKGROUND_PRIMARY_HOVER,
  BACKGROUND_PRIMARY_DISABLED,
  BACKGROUND_SECONDARY,
  BACKGROUND_SECONDARY_HOVER,
  BACKGROUND_SECONDARY_DISABLED,
  BACKGROUND_DANGER,
  BACKGROUND_DANGER_HOVER,
  BACKGROUND_DANGER_DISABLED,
  BACKGROUND_INPUT,
};
