/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface WzButton {
      'destructive': boolean;
      'primary': boolean;
    }
  }

  interface HTMLWzButtonElement extends StencilComponents.WzButton, HTMLStencilElement {}

  var HTMLWzButtonElement: {
    prototype: HTMLWzButtonElement;
    new (): HTMLWzButtonElement;
  };
  interface HTMLElementTagNameMap {
    'wz-button': HTMLWzButtonElement;
  }
  interface ElementTagNameMap {
    'wz-button': HTMLWzButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wz-button': JSXElements.WzButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface WzButtonAttributes extends HTMLAttributes {
      'destructive'?: boolean;
      'primary'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface WzText {
      'h200': boolean;
      'h300': boolean;
      'h400': string;
      'h500': boolean;
      'h600': boolean;
      'h700': boolean;
    }
  }

  interface HTMLWzTextElement extends StencilComponents.WzText, HTMLStencilElement {}

  var HTMLWzTextElement: {
    prototype: HTMLWzTextElement;
    new (): HTMLWzTextElement;
  };
  interface HTMLElementTagNameMap {
    'wz-text': HTMLWzTextElement;
  }
  interface ElementTagNameMap {
    'wz-text': HTMLWzTextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wz-text': JSXElements.WzTextAttributes;
    }
  }
  namespace JSXElements {
    export interface WzTextAttributes extends HTMLAttributes {
      'h200'?: boolean;
      'h300'?: boolean;
      'h400'?: string;
      'h500'?: boolean;
      'h600'?: boolean;
      'h700'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
