/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface CsButton {
      'csDisabled': boolean;
      'csName': string;
      'csType': string;
    }
  }

  interface HTMLCsButtonElement extends StencilComponents.CsButton, HTMLStencilElement {}

  var HTMLCsButtonElement: {
    prototype: HTMLCsButtonElement;
    new (): HTMLCsButtonElement;
  };
  interface HTMLElementTagNameMap {
    'cs-button': HTMLCsButtonElement;
  }
  interface ElementTagNameMap {
    'cs-button': HTMLCsButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cs-button': JSXElements.CsButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface CsButtonAttributes extends HTMLAttributes {
      'csDisabled'?: boolean;
      'csName'?: string;
      'csType'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
