/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface WlButton {
      'destructive': boolean;
      'primary': boolean;
    }
  }

  interface HTMLWlButtonElement extends StencilComponents.WlButton, HTMLStencilElement {}

  var HTMLWlButtonElement: {
    prototype: HTMLWlButtonElement;
    new (): HTMLWlButtonElement;
  };
  interface HTMLElementTagNameMap {
    'wl-button': HTMLWlButtonElement;
  }
  interface ElementTagNameMap {
    'wl-button': HTMLWlButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wl-button': JSXElements.WlButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface WlButtonAttributes extends HTMLAttributes {
      'destructive'?: boolean;
      'primary'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface WlText {

    }
  }

  interface HTMLWlTextElement extends StencilComponents.WlText, HTMLStencilElement {}

  var HTMLWlTextElement: {
    prototype: HTMLWlTextElement;
    new (): HTMLWlTextElement;
  };
  interface HTMLElementTagNameMap {
    'wl-text': HTMLWlTextElement;
  }
  interface ElementTagNameMap {
    'wl-text': HTMLWlTextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wl-text': JSXElements.WlTextAttributes;
    }
  }
  namespace JSXElements {
    export interface WlTextAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
