version: 2

npm_login: &npm_login
  run:
    name: Login to NPM
    command: |
      npm config set @wizeline:registry=https://verdaccio.wizeline.sh
      npm config set //verdaccio.wizeline.sh/:_authToken=$NPM_TOKEN

jobs:
  dependency_install:
    docker: &yarn_defaults
    - image: node:8.7.0
    steps:
    - checkout
    - *npm_login
    - restore_cache: &restore_yarn_cache
        keys:
        - v2-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v2-yarn-cache-{{ .Branch }}
        - v2-yarn-cache-master
        - v2-yarn-cache
    - run:
        name: Build
        command: cd design-system && yarn
    - save_cache:
        key: v2-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
  test:
    docker: *yarn_defaults
    steps:
    - checkout
    - restore_cache: *restore_yarn_cache
    - run:
        name: Unit test
        command: cd design-system && yarn && yarn run test
workflows:
  version: 2
  continuous_integration:
    jobs:
    - dependency_install:
        context: ppm-js
    - test:
        context: ppm-js
        requires:
        - dependency_install

