version: 2

jobs:
  cd_to_dir:
    docker: &yarn_defaults
    steps:
    - run:
        name: Change to Design System directory
        command: cd design-system/
  dependency_install:
    docker: *yarn_defaults
    - image: node:8.7.0
    steps:
    - checkout
    - run:
        name: Login to NPM
        command: |
          npm config set @wizeline:registry=https://verdaccio.wizeline.sh
          npm config set //verdaccio.wizeline.sh/:_authToken=$NPM_TOKEN
    - restore_cache: &restore_yarn_cache
        keys:
        - v2-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v2-yarn-cache-{{ .Branch }}
        - v2-yarn-cache-master
        - v2-yarn-cache
    - run: yarn
    - save_cache:
        key: v2-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
  test:
    docker: *yarn_defaults
    steps:
    - checkout
    - restore_cache: *restore_yarn_cache
    - run:
        name: Unit test
        command: yarn run test
  dangerjs:
    docker: *yarn_defaults
    environment:
      NODE_ENV: test
    steps:
    - checkout
    - restore_cache: *restore_yarn_cache
    - run:
        name: DangerJS
        command: yarn danger ci

workflows:
  version: 2
  continuous_integration:
    jobs:
    - cd_to_dir:
        context: ppm-js
    - dependency_install:
        context: ppm-js
        requires:
        - cd_to_dir
    - test:
        context: ppm-js
        requires:
        - dependency_install
    - dangerjs:
        context: ppm-js
        requires:
        - dependency_install
